# Generated by Gruntfile.coffee
window.assets =
  host:    "http://nessjon.s3.amazonaws.com"
  scripts: "http://nessjon.s3.amazonaws.com/scripts"
  styles:  "http://nessjon.s3.amazonaws.com/styles"
  images:  "http://nessjon.s3.amazonaws.com/images"
  fonts:   "http://nessjon.s3.amazonaws.com/fonts"