module.exports = (grunt, _) ->
  config = _.config
  assets = _.config.assets
  console.log(assets)

  # Define paths
  host    = config.cdn
  scripts = config.cdn + '/' + assets.js.dir.toString().replace(/\/$/,'')
  styles  = config.cdn + '/' + assets.css.dir.toString().replace(/\/$/,'')
  images  = config.cdn + '/' + assets.img.dir.toString().replace(/\/$/,'')
  fonts   = config.cdn + '/' + assets.font.dir.toString().replace(/\/$/,'')

  # Variables for scripts
  contents = [
    '# Generated by Gruntfile.coffee'
    'window.assets ='
    '  host:    "' + host + '"'
    '  scripts: "' + scripts + '"'
    '  styles:  "' + styles + '"'
    '  images:  "' + images + '"'
    '  fonts:   "' + fonts + '"'
  ]
  dest = assets.coffee.src + "_variables.coffee"
  grunt.file.write dest, contents.join "\n"
  grunt.log.writeln "File #{dest.cyan} created."

  # Variables for styles
  contents = [
    '// Generated by Gruntfile.coffee'
    '@host:   "' + host + '";'
    '@fonts:  "' + fonts + '";'
    '@images: "' + images + '";'
  ]
  dest = assets.less.src + "_variables.less"
  grunt.file.write dest, contents.join "\n"
  grunt.log.writeln "File #{dest.cyan} created."
