// Generated by CoffeeScript 1.6.1

/*
                       (_)
    _ __   ___  ___ ___ _  ___  _ __    ___ ___  _ __ ___
   | '_ \ / _ \/ __/ __| |/ _ \| '_ \  / __/ _ \| '_ ` _ \
   | | | |  __/\__ \__ \ | (_) | | | || (_| (_) | | | | | |
   |_| |_|\___||___/___/ |\___/|_| |_(_)___\___/|_| |_| |_|
                      _/ |
                     |__/                               
                                                        ;-)
*/


(function() {

  Modernizr.load({
    load: ['scripts/lib/jquery.min.js', 'scripts/lib/underscore.min.js', 'scripts/lib/fastclick.min.js', 'scripts/lib/mousetrap.js', 'scripts/dev/fixie.min.js'],
    complete: function() {
      return jQuery(app.init());
    }
  });

  window.app = {};

  app.init = function() {
    app.setup();
    app.secretSong();
    app.countdown();
    app.navigation();
    app.slideshow();
    return $('html').addClass('ready');
  };

  app.setup = function() {
    new FastClick(document.body);
    _.templateSettings = {
      interpolate: /\#\{(.+?)\}/g
    };
    _.mixin({
      linkify: function(string) {
        string = string.replace(/(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig, "<a target='_blank' href='$1'>$1</a>");
        string = string.replace(/(^|\s)@(\w+)/g, "$1<a target='_blank' href='http://www.twitter.com/$2'>@$2</a>");
        return string = string.replace(/(^|\s)#(\w+)/g, "$1<a target='_blank' href='http://search.twitter.com/search?q=%23$2'>#$2</a>");
      }
    });
    if (navigator.userAgent.match(/iPhone/i) || navigator.userAgent.match(/iPod/i)) {
      (jQuery('html')).addClass('iphone');
    }
    return app.transitionEnd = 'webkitTransitionEnd otransitionend oTransitionEnd msTransitionEnd transitionend';
  };

  app.navigation = function() {
    $('header[role=banner] a.menu').on('click', function(e) {
      e.preventDefault();
      e.stopPropagation();
      return $('html').toggleClass('menu');
    });
    $(document).on('click', 'html.menu', function(e) {
      if (!$(e.target).parents('nav[role=navigation]').length) {
        return $('html').removeClass('menu');
      }
    });
    $('nav[role=navigation] > ul > li > a').on('click', function(e) {
      var $nav, href;
      e.preventDefault();
      $nav = $(this).next('nav');
      if ($nav.height() === 0) {
        $nav.closest('ul').find('> li > nav').height(0);
        $nav.height($nav.find('ul:first').height());
        return $nav.hide().show();
      } else {
        $('html').removeClass('menu');
        href = $(this).attr('href');
        return $('html, body').animate({
          scrollTop: $(href).offset().top
        }, 500, function() {
          return window.location.hash = href;
        });
      }
    });
    $(document).on('swipe', function(e) {
      if (e.direction === 'left') {
        $('html').addClass('menu');
      }
      if (e.direction === 'right') {
        return $('html').removeClass('menu');
      }
    });
    $(window).resize(function() {
      return $('nav[role=navigation]').height($('html').height() * 1.3);
    });
    return $(window).resize();
  };

  app.countdown = function() {
    return $('.countdown').each(function() {
      var $countdown, date, day, futureTime, hour, minute, month, time, year;
      $countdown = $(this);
      date = $countdown.attr("rel").split(" ")[0];
      time = $countdown.attr("rel").split(" ")[1];
      year = parseInt(date.split("-")[0], 10);
      month = parseInt(date.split("-")[1], 10) - 1;
      day = parseInt(date.split("-")[2], 10);
      hour = parseInt(time.split(":")[0], 10);
      minute = parseInt(time.split(":")[1], 10);
      futureTime = Date.UTC(year, month, day, hour, minute, 0);
      app.updateCountdown($countdown, futureTime);
      return setInterval(function() {
        return app.updateCountdown($countdown, futureTime);
      }, 5000);
    });
  };

  app.updateCountdown = function($countdown, futureTime) {
    var currentTime, d, days, daysFloat, hours, hoursFloat, minutes, minutesFloat;
    d = new Date();
    currentTime = Date.UTC(d.getFullYear(), d.getMonth(), d.getDate(), d.getHours(), d.getMinutes(), d.getSeconds(), d.getMilliseconds());
    daysFloat = (futureTime - currentTime) / 86400000;
    days = parseInt(daysFloat, 10);
    if (days < 0) {
      days = 0;
    }
    hoursFloat = (daysFloat - days) * 24;
    hours = parseInt(hoursFloat, 10);
    if (hours < 0) {
      hours = 0;
    }
    minutesFloat = (hoursFloat - hours) * 60;
    minutes = parseInt(minutesFloat, 10);
    if (minutes < 0) {
      minutes = 0;
    }
    $countdown.find("dd:nth-of-type(1) figure").text(days);
    $countdown.find("dd:nth-of-type(2) figure").text(hours);
    return $countdown.find("dd:nth-of-type(3) figure").text(minutes);
  };

  app.secretSong = function() {
    return Mousetrap.bind("z o o", function() {
      return $("body").append("<embed src=files/secret.mp3 autostart=true loop=false width=2 height=0>");
    });
  };

  app.slideshow = function() {
    return $('div.hero').each(function() {
      var $hero, id,
        _this = this;
      $hero = $(this);
      $hero.find('li:first').addClass('active');
      app.slideshow.advance = function() {
        var $curr, $prev;
        $prev = $hero.find('li:first');
        $curr = $prev.next('li');
        $curr.addClass('active');
        return $prev.addClass('previous').on(app.transitionEnd, function() {
          return $prev.off().detach().removeClass('active previous').appendTo($curr.parent());
        });
      };
      id = setInterval(app.slideshow.advance, 7000);
      return $('header[role=banner] h1 a').on('click', function(e) {
        e.preventDefault();
        return app.slideshow.advance();
      });
    });
  };

}).call(this);
